### ISSUE TITLE
SafeDevice.isSafeDevice throws an exception

### ISSUE THREAD

**Issue by kmusham** [ufukhawk/safe_device#10]
SafeDevice.isSafeDevice throws following exception. Same behavior on both Android Emulator and Pixel 2 real device.
  
I/flutter ( 8131): SafeDevice:: MissingPluginException(No implementation found for method canMockLocation on channel safe_device), #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
I/flutter ( 8131): <asynchronous suspension>
I/flutter ( 8131): #1      SafeDevice.isSafeDevice (package:safe_device/safe_device.dart:38:34)

I'm using  safe_device: ^1.0.8 

Any recommendations?

**Comment by Amr1440** [comment]
same issue still existing 
safe_device: ^1.1.1
