### ISSUE TITLE
The package considers all ios devices as jail broken 

### ISSUE THREAD

**Issue by ahmadkhedr** [ufukhawk/safe_device#12]
The package considers all ios devices as having an issue even if the device is real and not jailbroken.
Edit:
Something is wrong with the option isSafeDevice only ...even if other checks says that the phone is safe and cool, the isSafeDevice is always false,and this is only on ios

**Comment by ufukhawk** [comment]
I've tested it many times and haven't found such a problem, have you jailbroken your device once before?

**Comment by ufukhawk** [comment]
safe_device: ^1.1.0
