### ISSUE TITLE
After install, canMockLocation always returns true on the first check. But after that it works completely fine.

### ISSUE THREAD

**Issue by afiqezio** [ufukhawk/safe_device#14]
I am using safe_device: ^1.1.0

**Comment by ravitejaavv** [comment]
Hello,

Even I am facing same issue. Is there any update on this bug?

**Comment by ufukhawk** [comment]
What is your device model? I couldn't see this error on my own test devices?

**Comment by afiqezio** [comment]
Huawei devices which are Huawei nova 5t and Honor 8X

**Comment by ravitejaavv** [comment]
> What is your device model? I couldn't see this error on my own test devices?

Samsung Galaxy A52S

**Comment by leeancognixus** [comment]
Any work around to fix this issue?

**Comment by syasarpinarci** [comment]
This issue is still relevant, I am facing it with multiple devices such as Galaxy S21. Is there a solution posted for the issue to be closed?
