### ISSUE TITLE
a method to show program is running on windows 11 wsa

### ISSUE THREAD

**Issue by MetaiR** [ufukhawk/safe_device#18]
hi, currently your project doesn't consider windows 11 WSA as an emulator.
I think it must be considered as an emulator and if this is not the case, at least it must have some method to show if this program is running on it or not.

this is essential for projects with some security restrictions. when you install the application on WSA almost every access restriction such as the private folder for application contents, disabling screen capture, etc, become useless

**Comment by MetaiR** [comment]
@ufukhawk any idea?

**Comment by Joseph-Nathan** [comment]
any news ?
