### ISSUE TITLE
Wrong validation for rooted devices

### ISSUE THREAD

**Issue by Rodrigolmti** [ufukhawk/safe_device#19]
Hi, I'm using an Android phone with Lineage OS which is not rooted neither using something like Magisk, using a custom room not necessary imposes that the user have rooted device nor impose security treats.

Basically, this lib is preventing users to access some application on a faulty validation.

Suggestion narrow down the rootBeer class validation to properly check if the device is rooted.

**Comment by allanwolski-openco** [comment]
The same problem here. Any updates?

**Comment by ufukhawk** [comment]
up 1.1.2
