### ISSUE TITLE
safe_device uses Trust-location library and it is causing ANR when used in the same project with the background_locator_2 library

### ISSUE THREAD

**Issue by tulioccalazans** [ufukhawk/safe_device#26]
Hi, your library is causing ANR in my project and it is possible that it causes the same problem in other libraries that use device location.

```
I/locator_exampl(19665): Thread[3,tid=19672,WaitingInMainSignalCatcherLoop,Thread*=0x7de5016400,peer=0x17ec0020,"Signal Catcher"]: reacting to signal 3
I/locator_exampl(19665): 
I/locator_exampl(19665): Wrote stack traces to '[tombstoned]'
```

So that you can test it, download my [FORK](https://github.com/tulioccalazans/background_locator_fixed) from the [background_locator_2](https://pub.dev/packages/background_locator_2) project and add your library in the pubspec.yaml file of the "example" project:

>   background_locator_2:
>     path: ../
> 
>   path_provider: ^2.0.8
>   location_permissions: ^3.0.0+1
> 
>  **safe_device: ^1.1.2 # OR trust_location: ^2.0.13**

In the example project, when you press the "Start" button, you will notice that the app freezes.

PS: 

I noticed this problem when testing your library. Upon investigation, I noticed that the problem is related to the trust_location library (which your library uses).

To avoid this ANR, I [FORK ](https://github.com/tulioccalazans/safe_device) your project, removing the [trust_location](https://pub.dev/packages/trust_location) and commenting out all its usage, since I don't have the need to check the use of mock locations in my project.

I reported the issue as [an issue](https://github.com/wongpiwat/trust-location/issues/19) on the trust_location project as well.

**Comment by IonVillarreal** [comment]
hi i have the same ANR warning problem on google play store

for now I'm using this library (but it doesn't check external storage)

https://pub.dev/packages/flutter_jailbreak_detection
