### ISSUE TITLE
canMockLocation and isRealDevice return wrong result

### ISSUE THREAD

**Issue by fahmisatrio** [ufukhawk/safe_device#27]
First, similar with this issue
On the first check, canMockLocation always returns true. #13
https://github.com/ufukhawk/safe_device/issues/13

and
On the first check, canMockLocation always returns true.
https://github.com/ufukhawk/safe_device/issues/8

in Android, sometimes canMockLocation give true result even if the user didn't using any mock location applications.

Second, related with isRealDevice
when we tested the application using LD Player, it's always return false and recognized the user as RealDevice.

I'm using latest libs available in Pub.dev
safe_device: ^1.1.2

Thanks for your hardwork in this lib.
really appreciate.

Rgds,

**Comment by bagusandrewijaya** [comment]
same problem you have any solution or any dependency?

**Comment by ufukhawk** [comment]
1.1.3

**Comment by hanifmhd** [comment]
@ufukhawk should i downgrade to version 1.1.3?
