### ISSUE TITLE
isSafeDevice logic is confusing

### ISSUE THREAD

**Issue by icgoogo** [ufukhawk/safe_device#28]
hi, i just find out that the logic for isSafeDevice is absolutely confusing 

`return isJailBroken || !isRealDevice || canMockLocation;`

the docs indicates that :
`// Check if device violates any of the above`

but the variable name is `isSafeDevice`

I suggest to swap either the variable name or the return logic  @ufukhawk

**Comment by ufukhawk** [comment]
safe_device: ^1.1.5
