### ISSUE TITLE
Pixel 6 simulator is detected as a rooted device

### ISSUE THREAD

**Issue by Allyanora** [ufukhawk/safe_device#32]
I don't have any other issues with other Pixel simulators (3a or 4 for example), only this one in particular has this issue. 

Tested on two macbooks, package version 1.1.4, Flutter version 3.10.6. 
If you need more information, let me know.

**Later edit**: reproduces on Pixel 5, both devices using API level 33.

**Comment by ufukhawk** [comment]
safe_device: ^1.1.5
