### ISSUE TITLE
Collision with geolocator in Android release mode

### ISSUE THREAD

**Issue by martin-braun** [ufukhawk/safe_device#33]
As soon as this is used with `geolocator`, Android release builds will be stuck with a white screen for 5 - 40 seconds on app start. 

Eventually logcat reports something among the lines: `Skipped 1800 frames!  The application may be doing too much work on its main thread.`

See https://github.com/Baseflow/flutter-geolocator/issues/1296#issuecomment-1674099396 for details.

**Comment by martin-braun** [comment]
I also noticed that `safe_device` doesn't play nice with `cached_network_image`. Images would take very long to load, even in debug mode. Eventually everything would load up, but only after a long freeze.

As soon as I removed `safe_device`, things would work properly again and my app would become snappy. 

The native bits of this library are hogging a lot. It doesn't seem to play nice with other packages.

**Comment by JeroenWeener** [comment]
Jeroen here, one of the maintainers of `geolocator`. We briefly looked into the issue mentioned in Baseflow/flutter-geolocator/issues/1296 but were unable to reproduce the issue. We think the issue is likely with `safe_device`, as multiple plugins have reported the same issue when being used in conjunction with this plugin.

**Comment by michaelnabil230** [comment]
I'm experiencing the same problem with `geolocator: ^10.0.0` and `safe_device: ^1.1.4`. Has anyone found a solution to resolve this issue? Your help would be greatly appreciated.

**Comment by martin-braun** [comment]
@michaelnabil230 I swapped `safe_device` with `device_info_plus`. If you don't need root detection, this is probably the best for you, too.

**Comment by qwadrox** [comment]
Same geolocator: 10.0.1 with safe_device: 1.1.4
Reproduced here if interested: 
https://github.com/qwadrox/firebase_flutter_repoduce_bug/tree/bug/safe_device_geolocator_bug

**Comment by ufukhawk** [comment]
safe_device: ^1.1.5
