### ISSUE TITLE
The program cannot run after adding dependencies

### ISSUE THREAD

**Issue by BodenTide** [ufukhawk/safe_device#41]
Some of my environment parameters

Flutter version: Flutter 3.13.9
safe_device: ^1.1.4

After starting the program, the following error appears
![image](https://github.com/ufukhawk/safe_device/assets/137751112/3bc9f3df-55c0-4ac3-8772-6b380e72b41f)

what should i do i need help！！！

**Comment by ufukhawk** [comment]
safe_device: ^1.1.5
