### ISSUE TITLE
Safe device has conflict with geolocator package

### ISSUE THREAD

**Issue by eb-so** [ufukhawk/safe_device#42]
When adding this plugin to an app that uses the geolocator package it produce a weird issue that affect the location permissing 
see this [issue](https://github.com/Baseflow/flutter-geolocator/issues/1243) for more information

**Comment by lorenzolanciok** [comment]
same problem here!

**Comment by ufukhawk** [comment]
safe_device: ^1.1.5

**Comment by satella12** [comment]
how fix it ?
