### ISSUE TITLE
Error while compiling with compileSdkVersion 34

### ISSUE THREAD

**Issue by DannyFilo** [ufukhawk/safe_device#44]
in compileSdkVersion 34 - namespace is required in android/app/build.gradle - in android section
normally you can add namespace 'com.xamdesign.safe_device' - appreciate this update

I have the following error and can't use the library

A problem occurred configuring project ':safe_device'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by alberto-cappellina** [comment]
hi @DannyFilo my pull request should fix your issue https://github.com/ufukhawk/safe_device/pull/46

**Comment by ufukhawk** [comment]
safe_device: ^1.1.7
