### ISSUE TITLE
Android: add namespace to support AGP 8

### ISSUE THREAD

**Issue by fu89-team** [ufukhawk/safe_device#45]
Lib is not usable with Gradle 8 (Android), just add namespace to build.gradle.
Thanks.

**Comment by alberto-cappellina** [comment]
hi @fu89-team, my pullrequest should fix your issue https://github.com/ufukhawk/safe_device/pull/46

**Comment by OliverNarramore** [comment]
Yes please

**Comment by ufukhawk** [comment]
https://pub.dev/packages/safe_device @OliverNarramore
