### ISSUE TITLE
The plugin `safe_device` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by aguitto** [ufukhawk/safe_device#5]
Since Flutter 2.5.0 it should be upgraded with Android V2 embedding.

Here the error : 

The plugin `safe_device` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: [](https://flutter.dev/go/android-plugin-migration.)

**Comment by alifgiant** [comment]
I open a PR #7 for it
