### ISSUE TITLE
 MissingPluginException(No implementation found for method canMockLocation on channel safe_device)

### ISSUE THREAD

**Issue by giorell** [ufukhawk/safe_device#6]
As the title says, can't find canMockLocation channel.

Running on real developer enabled Pixel 4a device. Running Android 11.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.0)
[✓] Connected device (3 available)

Exception from Flutter:
I/flutter (22322): MissingPluginException(No implementation found for method canMockLocation on channel safe_device)

Tried deleting app, reinstalling, and restarting vscode. None of restarts or reinstalls worked.

Code I'm using:

 static Future<bool> isDeviceCompromised() async {
    bool isCompromised = false;
    try {
      isCompromised = await SafeDevice.isSafeDevice;
    } catch (error) {
      print(error);
      rethrow;
    }
    print('isCompromised(): $isCompromised');

    return isCompromised;
  }

Please let me know if you need more info.

**Comment by ufukhawk** [comment]
[safe_device 1.0.8](https://pub.dev/packages/safe_device )

**Comment by Sunzhuokai** [comment]
not work in 1.0.8

**Comment by Djcharles26** [comment]
same in 1.0.8

**Comment by iusn** [comment]
same in 1.1.1

**Comment by Amr1440** [comment]
same in 1.1.1
I don't know why @ufukhawk you close the issue before confirming that its solved already ?!
